---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
  # https://github.com/yannickcr/eslint-plugin-react
  - react

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

rules:
  no-console: 0
  react/prop-types: 0
  arrow-parens: 0
  quotes:
    - error
    - double


